services:
  form-server:
    container_name: form-server
    build: .
    depends_on:
      form-db:
        condition: service_healthy
    ports:
      - 3007:3007
    env_file:
      - ./configs/docker.dev.env
    environment:
      POSTGRES_URI: postgres://postgres:test@form-db:5432/postgres?search_path=form

  form-db:
    container_name: form-db
    image: postgres:alpine
    ports:
      - 5447:5432
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d postgres"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s
