version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:prepare && bundle exec rails s -p 3003 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
      FILE_SERVICE_API: http://file-service-api-1:3008
      AUTH_SERVICE_API: http://host.docker.internal:3001
    ports:
      - "3003:3003"
    depends_on:
      - db
networks:
  default:
    name: backend
