services:
  notification-db:
    container_name: notification-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d postgres"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s
  notification-server:
    container_name: notification-server
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3006 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      POSTGRES_HOST: notification-db
      POSTGRES_PASSWORD: password
      AUTH_SERVICE_API: http://auth-server:3001
    ports:
      - 3006:3006
    depends_on:
      notification-db:
        condition: service_healthy
