services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:prepare && bundle exec rails s -p 3005 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
    ports:
      - "3005:3005"
    depends_on:
      - db
networks:
  default:
    name: backend
