default: &default
  adapter: postgresql
  encoding: unicode
  database: course_development
  host: <%= ENV['POSTGRES_HOST'] %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
