services:
  db:
    container_name: user-db
    image: postgres:alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d postgres"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s
