services:
  user-server:
    container_name: user-server
    build: .
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - 3002:3002
    env_file:
      - ./configs/docker.dev.env
    environment:
      POSTGRES_URI: postgres://postgres:test@user-db:5432/postgres?search_path=user

  user-db:
    container_name: user-db
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres -d postgres"]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s
